projects:
  functionsonsteroids:
    schemaPath: amplify/backend/api/functionsonsteroids/build/schema.graphql
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/API.service.ts
        docsFilePath: src/graphql
        region: eu-central-1
        apiId: null

  fosDeleteAllCompleted:
    schemaPath: amplify/backend/api/functionsonsteroids/build/schema.graphql
    includes:
      - amplify/backend/function/fosDeleteAllCompleted/lib/generated/*.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: amplify/backend/function/fosDeleteAllCompleted/lib/generated/types.ts
        docsFilePath: amplify/backend/function/fosDeleteAllCompleted/lib/generated/
        region: eu-central-1
        apiId: null

  fosMarkAllAsComplete:
    schemaPath: amplify/backend/api/functionsonsteroids/build/schema.graphql
    includes:
      - amplify/backend/function/fosMarkAllAsComplete/lib/generated/*.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: amplify/backend/function/fosMarkAllAsComplete/lib/generated/types.ts
        docsFilePath: amplify/backend/function/fosMarkAllAsComplete/lib/generated/
        region: eu-central-1
        apiId: null

  fosToggleIsCompleted:
    schemaPath: amplify/backend/api/functionsonsteroids/build/schema.graphql
    includes:
      - amplify/backend/function/fosToggleIsCompleted/lib/generated/*.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: amplify/backend/function/fosToggleIsCompleted/lib/generated/types.ts
        docsFilePath: amplify/backend/function/fosToggleIsCompleted/lib/generated/
        region: eu-central-1
        apiId: null

extensions:
  amplify:
    version: 3
